/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtRouteImport } from './routes/et'
import { Route as RuRouteImport } from './routes/ru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtRoute = EtRouteImport.update({
  id: '/et',
  path: '/et',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/et': typeof EtRoute
  '/ru': typeof RuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/et': typeof EtRoute
  '/ru': typeof RuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/et': typeof EtRoute
  '/ru': typeof RuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/et' | '/ru'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/et' | '/ru'
  id: '__root__' | '/' | '/et' | '/ru'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EtRoute: typeof EtRoute
  RuRoute: typeof RuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/et': {
      id: '/et'
      path: '/et'
      fullPath: '/et'
      preLoaderRoute: typeof EtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EtRoute: EtRoute,
  RuRoute: RuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
